# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HTR United Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install htr-united-metadata-generator
    - name: Run Report
      run: |
        humGenerator --group **/*.xml --github-envs --parse page
        cat envs.txt >> $GITHUB_ENV
    - name: Create Awesome Badge
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "3c059562743dbd31b7b71cb41f74347c"
        filename: "rep_chars.json"
        label: "Transcribed Characters"
        message: ${{ env.HTRUNITED_CHARS }}
        color: informational
        style: "flat-square"
    - name: Create Awesome Badge for LINES
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "3c059562743dbd31b7b71cb41f74347c"
        filename: "rep_lines.json"
        label: "Transcribed Lines"
        message: ${{ env.HTRUNITED_LINES }}
        color: informational
        style: "flat-square"
    - name: Create Awesome Badge for REGIONS
      uses: Schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "3c059562743dbd31b7b71cb41f74347c"
        filename: "rep_regions.json"
        label: "Number of regions"
        message: ${{ env.HTRUNITED_REGNS }}
        color: informational
        style: "flat-square"
